# Generated by Django 5.2.10 on 2026-04-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_role_and_purchase_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbooking',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Кардио-тренировки'), ('strength', 'Силовые тренировки'), ('yoga', 'Йога и растяжка'), ('functional', 'Функциональные тренировки'), ('gymnastics', 'Гимнастика'), ('pilates', 'Пилатес'), ('crossfit', 'Кроссфит'), ('aqua', 'Аквааэробика')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingBookingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Ожидает решения'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('old_workout_type', models.CharField(choices=[('cardio', 'Кардио-тренировки'), ('strength', 'Силовые тренировки'), ('yoga', 'Йога и растяжка'), ('functional', 'Функциональные тренировки'), ('gymnastics', 'Гимнастика'), ('pilates', 'Пилатес'), ('crossfit', 'Кроссфит'), ('aqua', 'Аквааэробика')], max_length=20)),
                ('old_date', models.DateField()),
                ('old_time', models.TimeField()),
                ('old_trainer', models.CharField(blank=True, max_length=100)),
                ('old_comments', models.TextField(blank=True)),
                ('new_workout_type', models.CharField(choices=[('cardio', 'Кардио-тренировки'), ('strength', 'Силовые тренировки'), ('yoga', 'Йога и растяжка'), ('functional', 'Функциональные тренировки'), ('gymnastics', 'Гимнастика'), ('pilates', 'Пилатес'), ('crossfit', 'Кроссфит'), ('aqua', 'Аквааэробика')], max_length=20)),
                ('new_date', models.DateField()),
                ('new_time', models.TimeField()),
                ('new_trainer', models.CharField(blank=True, max_length=100)),
                ('new_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_updates', to='users.trainingbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
