# Generated by Django 5.2.10 on 2026-04-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_shopproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestatushistory',
            name='status',
            field=models.CharField(choices=[('created', 'Оформлен'), ('processing', 'В обработке'), ('ready', 'Готово к выдаче'), ('delivered', 'Выдано'), ('cancelled', 'Отменён')], max_length=30),
        ),
    ]
